create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  category text not null,
  description text not null,
  price numeric(12,2) not null check (price > 0),
  stock integer not null default 0 check (stock >= 0),
  image_url text not null,
  featured boolean not null default false,
  active boolean not null default true,
  created_by text not null,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

create policy "Public products are readable"
on public.products for select
using (active = true);

create index if not exists products_active_created_idx
on public.products (active, created_at desc);
